#argocd app create devops-apps --repo https://github.com/fpultera/apps.git --path "0-seeds" --dest-namespace devops-apps --dest-server https://kubernetes.default.svc
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-apps
  source: 
    repoURL: https://github.com/fpultera/apps.git
    targetRevision: HEAD
    path: 0-seeds
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-apps
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
#test
