apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook
  namespace: argo-events
spec:
  rules:
  - host: webhook.kub
    http:
      paths:
      - path: /
        backend:
          serviceName: webhook-eventsource-svc
          servicePort: 12000
