apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://getredash.github.io/contrib-helm-chart/
    targetRevision: 3.0.0
    chart: redash
  destination:
    server: https://kubernetes.default.svc
    namespace: redash
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
