apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-slack
  namespace: argo-events
spec:
  service:
    ports:
    - port: 12001
      targetPort: 12001
  webhook: 
    example:
      endpoint: /example
      method: POST
      port: "12000"