apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: v0.0.104
    chart: reloader
    helm:
      values: |
        reloader:
          ignoreConfigMaps: true
          ignoreNamespaces: "devops-apps"
  destination:
    server: https://kubernetes.default.svc
    namespace: stakater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true