apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision:  0.5.0
    chart: vault
    helm:
      values: |
        server:
          standalone:
            enable: "-"
            config: |
              extraEnv:
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /vault/sa/key.json
              extraVolumes:
              - name: vault-gcs-sa
                secret:
                  secretName: gcp-secret
              extraVolumeMounts:
              - name: vault-gcs-sa
                mountPath: /vault/sa
                readOnly: true
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              # storage "file" {
              #   path = "/vault/data"
              # }
              storage "gcs" {
                bucket = "backup-vault-storage"
                credentials_file = /vault/sa/key.json
              }
        # server:
        #   affinity: ""
        #   ha:
        #     enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
