apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision:  0.5.0
    chart: vault
    helm:
      values: |
        server:
          extraVolumes:
            - type: secret
              name: gcp-secret
              path: null # default is `/vault/userconfig`
          standalone:
            enable: "-"
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              # storage "file" {
              #   path = "/vault/data"
              # }
              storage "gcs" {
                bucket = "backup-vault-storage"
                credentials = "/vault/userconfig/gcp-secret/quiet-era-330215-ac88592a8022.json"
              }
        # server:
        #   affinity: ""
        #   ha:
        #     enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
