apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: munditrade-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/munditrade/devops-argocd-apps.git'
    path: 2-munditrade
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
