apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: slack-ingress
  namespace: argo-events
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /example
          backend:
            serviceName: webhook-eventsource-svc
            servicePort: 12000