apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: slack-trigger
        slack:
          channel: general
          message: hello world
          slackToken:
            key: token
            name: slack-secret
      parameters:
        - src:
            dependencyName: test-dep
            dataKey: body.channel
          dest: slack.channel
        - src:
            dependencyName: test-dep
            dataKey: body.message
          dest: slack.message