apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "db.movetokube.com/v1alpha1",
          "kind": "Postgres",
          "metadata": {
            "name": "my-db",
            "namespace": "app"
          },
          "spec": {
            "database": "test-db",
            "dropOnDelete": false,
            "masterRole": "test-db-group",
            "schemas": [
              "stores",
              "customers"
            ]
          }
        },
        {
          "apiVersion": "db.movetokube.com/v1alpha1",
          "kind": "PostgresUser",
          "metadata": {
            "name": "my-db-user",
            "namespace": "app"
          },
          "spec": {
            "database": "my-db",
            "privileges": "OWNER",
            "role": "username",
            "secretName": "my-secret"
          }
        }
      ]
    capabilities: Basic Install
  name: ext-postgres-operator.v0.4.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Postgres is the Schema for the postgres API
      kind: Postgres
      name: postgres.db.movetokube.com
      version: v1alpha1
    - description: PostgresUser is the Schema for the postgresusers API
      kind: PostgresUser
      name: postgresusers.db.movetokube.com
      version: v1alpha1
  description: Placeholder description
  displayName: Ext Postgres Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - ext-postgres-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - db.movetokube.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: ext-postgres-operator
      deployments:
      - name: ext-postgres-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ext-postgres-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ext-postgres-operator
            spec:
              containers:
              - command:
                - postgres-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ext-postgres-operator
                envFrom:
                - secretRef:
                    name: ext-postgres-operator
                image: movetokube/postgres-operator
                imagePullPolicy: Always
                name: ext-postgres-operator
                resources: {}
              serviceAccountName: ext-postgres-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: ext-postgres-operator.v0.4.1
  version: 0.4.3
