apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision:  0.5.0
    chart: vault
    helm:
      values: |
        server:
          extraEnvironmentVars:
            GOOGLE_CREDENTIALS: /vault/userconfig/gcp-secret-vault/gcp-secret-vault.json
            GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/gcp-secret-vault/gcp-secret-vault.json
          extraVolumes:
            - type: secret
              name: gcp-secret-vault
              path: null # default is `/vault/userconfig`
          standalone:
            enable: "-"
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "gcs" {
                bucket = "secrets-vault-data"
                ha_enabled    = "true"
              }
          ingress:
            enabled: true
            annotations: |
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
              acme.cert-manager.io/http01-edit-in-place: "true"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              cert-manager.io/issue-temporary-certificate: "true"
            hosts:
              - host: vault.example.dev
                paths:
                  - /
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.example.dev
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
