apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misecretos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fpultera/apps.git
    targetRevision: main
    path: secretos
  destination:
    server: https://kubernetes.default.svc
    namespace: misecreto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true