apiVersion: v1
kind: Service
metadata:
  name: web-cuca
spec:
  $patch: replace
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    role: service
    cuca: cuca
  type: ClusterIP