apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "db.movetokube.com/v1alpha1",
          "kind": "Postgres",
          "metadata": {
            "name": "my-db",
            "namespace": "app"
          },
          "spec": {
            "database": "test-db",
            "dropOnDelete": false,
            "masterRole": "test-db-group",
            "schemas": [
              "stores",
              "customers"
            ]
          }
        },
        {
          "apiVersion": "db.movetokube.com/v1alpha1",
          "kind": "PostgresUser",
          "metadata": {
            "name": "my-db-user",
            "namespace": "app"
          },
          "spec": {
            "database": "my-db",
            "privileges": "OWNER",
            "role": "username",
            "secretName": "my-secret"
          }
        }
      ]
    capabilities: Basic Install
    categories: Database
    containerImage: movetokube/postgres-operator:0.3
    description: Manage databases and roles in external PostgreSQL server or cluster
    repository: https://github.com/movetokube/postgres-operator
    createdAt: '2019-12-19T14:12:00Z'
  name: ext-postgres-operator.v0.4.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Represents a resource for managing external PostgreSQL database
          and associated group role
        displayName: postgres.db.movetokube.com
        kind: Postgres
        name: postgres.db.movetokube.com
        version: v1alpha1
      - description: Represents a resource for managing external PostgreSQL user role
        displayName: postgresusers.db.movetokube.com
        kind: PostgresUser
        name: postgresusers.db.movetokube.com
        version: v1alpha1
  description: "ext-postgres-operator is an external PostgreSQL database operator. This is a very light-weight basic operator which\ndoes not provide a PostgreSQL server, but rather manages databases inside an existing PostgreSQL database server (or cluster). \n## Features\r\n* Creates a database from a CR\r\n* Creates a role with random username and password from a CR\r\n* If the database exist, it will only create a role\r\n* Multiple user roles can own one database\r\n* Creates Kubernetes secret with postgres_uri in the same namespace as CR\r\n* Support for AWS RDS and Azure Database for PostgresSQL\r\n\r\n\r\n## Cloud specific configuration\r\n### AWS\r\nIn order for this operator to work correctly with AWS RDS, you need to set `POSTGRES_CLOUD_PROVIDER` to `AWS` either in \r\nthe ext-postgres-operator kubernetes secret or directly in the deployment manifest (`operator.yaml`).\r\n\r\n### Azure Database for PostgreSQL\r\nIn order for this operator to work correctly with Azure managed PostgreSQL database, two env variables needs to be provided for the operator:\r\n* `POSTGRES_CLOUD_PROVIDER` set to `Azure`\r\n* `POSTGRES_DEFAULT_DATABASE` set to your default database, i.e. `postgres`\r\n\r\n## CRs\r\n\r\n### Postgres\r\n```yaml\r\napiVersion: db.movetokube.com\/v1alpha1\r\nkind: Postgres\r\nmetadata:\r\n  name: my-db\r\n  namespace: app\r\nspec:\r\n  database: test-db # Name of database created in PostgreSQL\r\n  dropOnDelete: false # Set to true if you want the operator to drop the database and role when this CR is deleted\r\n  masterRole: test-db-group\r\n  schemas: # List of schemas the operator should create in database\r\n  - stores\r\n  - customers\r\n```\r\n\r\nThis creates a database called `test-db` and a role `test-db-group` that is set as the owner of the database.\r\nReader and writer roles are also created. These roles have read and write permissions to all tables in the schemas created by the operator, if any.\r\n\r\n### PostgresUser\r\n```yaml\r\napiVersion: db.movetokube.com\/v1alpha1\r\nkind: PostgresUser\r\nmetadata:\r\n  name: my-db-user\r\n  namespace: app\r\nspec:\r\n  role: username\r\n  database: my-db # This references the Postgres CR\r\n  secretName: my-secret\r\n  privileges: OWNER # Can be OWNER\/READ\/WRITE\r\n```\r\n\r\nThis creates a user role `username-<hash>` and grants role `test-db-group`, `test-db-writer` or `test-db-reader` depending on `privileges` property. Its credentials are put in secret `my-secret-my-db-user`.\r\n\r\n`PostgresUser` needs to reference a `Postgres` in the same namespace.\r\n\r\nTwo `Postgres` referencing the same database can exist in more than one namespace. The last CR referencing a database will drop the group role and transfer database ownership to the role used by the operator."
  displayName: Ext Postgres Operator
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - apps
              resourceNames:
                - ext-postgres-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - db.movetokube.com
              resources:
                - '*'
              verbs:
                - '*'
          serviceAccountName: ext-postgres-operator
      deployments:
        - name: ext-postgres-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: ext-postgres-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: ext-postgres-operator
              spec:
                containers:
                  - command:
                      - postgres-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: ext-postgres-operator
                    envFrom:
                      - secretRef:
                          name: ext-postgres-operator
                    image: movetokube/postgres-operator:0.2
                    imagePullPolicy: Always
                    name: ext-postgres-operator
                    resources: {}
                serviceAccountName: ext-postgres-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces

  links:
    - name: movetokube.com
      url: https://movetokube.com
  maintainers:
    - email: tomas@movetokube.com
      name: Tomas Adomavicius
  maturity: alpha
  provider:
    name: movetokube.com
  replaces: ext-postgres-operator.v0.3.0
  version: 0.4.1